# Copyright 2022 Catalogic Software
# See LICENSE file for licensing details.

options:
  clusterid:
    default: ""
    description: clusterid used by target custer to get registered
    type: string
